languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Blog - Rener Rannieri"
logo = "img/logo-gradient.png"
description = "ğŸ‘‹ğŸ¾ OlÃ¡! Me chamo Rener e esse Ã© meu Blog.Nesse espaÃ§o vocÃª vai encontrar artigos, ideias, pensamentos e experimentaÃ§Ãµes."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
name = "Rener Rannieri"
image = "img/author.jpg"
headline = "Designer de Produtos Digitais | Ilustrador"
bio = "Apaixonado por tecnologia, design e aprendizagem. A, e tem a alma de artista."
links = [
  { link = "https://renerrannieri.xyz" },
  { linkedin = "https://www.linkedin.com/in/rener-rannieri/" },
  { medium = "https://medium.com/@rener.rannieri" },
  { email = "mailto:rannieri.rener@gmail.com" },
]
 
